# Enable deep sleep support
CONFIG_ZMK_SLEEP=y

# enable the LCD Display
#CONFIG_ZMK_DISPLAY=y
CONFIG_LOG_BUFFER_SIZE=8192
CONFIG_LOG_STRATEGY_RAW=y
CONFIG_LOG_BLOCK_COUNT=16

# https://github.com/zmkfirmware/zmk/blob/main/app/boards/shields/nice_view/README.md#disable-custom-widget
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
#CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
#CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y

CONFIG_ZMK_STUDIO=y

CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_SELECT_OVER_BLE=y

## neuroslop ???
# USB-stack и CDC ACM (Virtual COM-port)
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y

# console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_USB_UART_CONSOLE=y

# Shell
#CONFIG_SHELL=y
#CONFIG_USB_DEVICE_INITIALIZE=y
