# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep. 
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=360000

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_SENSOR=y
CONFIG_PMW33XX=y
CONFIG_PMW33XX_3389=y
CONFIG_PMW33XX_TRIGGER_OWN_THREAD=y
CONFIG_ZMK_POINTING=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# enable the LCD Display
CONFIG_ZMK_DISPLAY=ys
# enable mouse support
#CONFIG_ZMK_MOUSE=y
#CONFIG_ZMK_MOUSE=y


# https://github.com/zmkfirmware/zmk/blob/main/app/boards/shields/nice_view/README.md#disable-custom-widget
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
#CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
#CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y

CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_SELECT_OVER_BLE=y

## neuroslop ???
# USB-stack и CDC ACM (Virtual COM-port)
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y

# console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_USB_UART_CONSOLE=y
# enable log
CONFIG_LOG=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

# Shell
#CONFIG_SHELL=y
#CONFIG_USB_DEVICE_INITIALIZE=y
