file_format: "1"
id: dactyl_manuform
name: Dactyl Manuform
type: shield
url: https://github.com/tuxy-streamer/zmk-config
requires: [pro_micro]
features:
  - keys
siblings:
  - dactyl_manuform_left
  - dactyl_manuform_right
